package com.github.TeamRocketBalleBalle.Ricktionary.Client;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author tiwar
 */
public class welcomescreen extends javax.swing.JPanel implements ActionListener {
    JTextField name = new JTextField("Enter Your Name...");
    JTextField ip = new JTextField("Enter IP...");

    static String clientname = "";
    static String clientip = "";

    /**
     * Creates new form NewJFrame
     */
    public welcomescreen() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException
                | IllegalAccessException
                | InstantiationException
                | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomescreen.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new welcomescreen());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        ImageIcon icon = new ImageIcon("Client/src/main/resources/logo.png");
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(1077, 767, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        // Variables declaration - do not modify

        JLabel nameLabel = new JLabel();
        JLabel ipLabel = new JLabel();
        JButton sendButton = new JButton();
        JLabel bg = new JLabel(scaledIcon);
        // JLabel jLabel3 = new javax.swing.JLabel();
        // setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1077, 767));

        name.setFont(
                new java.awt.Font("Tw Cen MT Condensed", Font.BOLD | Font.ITALIC, 18)); // NOI18N
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ip.setFont(new java.awt.Font("Tw Cen MT Condensed", Font.BOLD | Font.ITALIC, 18)); // NOI18N
        nameLabel.setFont(new java.awt.Font("Gabriola", Font.BOLD, 18)); // NOI18N
        nameLabel.setText("Name");
//        nameLabel.setForeground(Color.decode("#037AA4"));
//        nameLabel.setOpaque(true);
//        nameLabel.setBackground(Color.black);

        ipLabel.setFont(new java.awt.Font("Gabriola", Font.BOLD, 18)); // NOI18N
        ipLabel.setText("IP Address ");

        sendButton.setText("SUBMIT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        //                        .addGroup(
                        //                                layout.createSequentialGroup()
                        //                                        .addGap(450, 450, 450)
                        //                                        .addComponent(
                        //                                                jLabel3,
                        //
                        // javax.swing.GroupLayout.PREFERRED_SIZE,
                        //                                                250,
                        //
                        // javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(310, 310, 310)
                                        .addComponent(
                                                nameLabel,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                153,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(137, 137, 137)
                                        .addComponent(
                                                name,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                153,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(310, 310, 310)
                                        .addComponent(
                                                ipLabel,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                153,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(600, 600, 600)
                                        .addComponent(
                                                ip,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                153,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(473, 473, 473)
                                        .addComponent(
                                                sendButton,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                130,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                //                        .addComponent(
                //                                bg,
                //                                javax.swing.GroupLayout.PREFERRED_SIZE,
                //                                1077,
                //                                javax.swing.GroupLayout.PREFERRED_SIZE)
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        //                        .addGroup(
                        //                                layout.createSequentialGroup()
                        //                                        .addGap(10, 10, 10)
                        //                                        .addComponent(
                        //                                                jLabel3,
                        //
                        // javax.swing.GroupLayout.PREFERRED_SIZE,
                        //                                                100,
                        //
                        // javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(310, 310, 310)
                                        .addGroup(
                                                layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                        .LEADING)
                                                        .addComponent(
                                                                nameLabel,
                                                                javax.swing.GroupLayout
                                                                        .PREFERRED_SIZE,
                                                                50,
                                                                javax.swing.GroupLayout
                                                                        .PREFERRED_SIZE)
                                                        .addComponent(
                                                                name,
                                                                javax.swing.GroupLayout
                                                                        .PREFERRED_SIZE,
                                                                50,
                                                                javax.swing.GroupLayout
                                                                        .PREFERRED_SIZE))
                                        .addComponent(
                                                ipLabel,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                50,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(350, 350, 350)
                                        .addComponent(
                                                ip,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                50,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(579, 579, 579)
                                        .addComponent(
                                                sendButton,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                60,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                //                        .addComponent(
                //                                bg,
                //                                javax.swing.GroupLayout.PREFERRED_SIZE,
                //                                767,
                //                                javax.swing.GroupLayout.PREFERRED_SIZE)
                );
        bg.setBounds(new Rectangle(1077, 767));
        bg.setIcon(scaledIcon);
        add(bg);
        sendButton.addActionListener(this::actionPerformed);

        // pack();
        //        setVisible(true);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        clientip = ip.getText();
        clientname = name.getText();
        System.out.println(clientname + " " + clientip);
        //        new GameScreen().Name.setText(clientname);

    }

    // End of variables declaration
}
