package com.github.TeamRocketBalleBalle.Ricktionary.Client;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/** @author tiwar */
public class welcomescreen extends javax.swing.JFrame implements ActionListener {
    public String Playername;
    public String PlayerIP;
    private javax.swing.JTextField name;
    private JTextField ip;

    /**
     * Creates new form NewJFrame
     */
    public welcomescreen() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException
                | IllegalAccessException
                | InstantiationException
                | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomescreen.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new welcomescreen());
    }

    public void ClientName(String name) {
        Playername = name;
    }

    public void ClientIP(String ip) {
        PlayerIP = ip;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        ImageIcon icon = new ImageIcon("Client/src/main/resources/image0.gif");
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(1077, 767, Image.SCALE_DEFAULT);
        ImageIcon scaledIcon = new ImageIcon(imgscale);

        // Variables declaration - do not modify
        name = new JTextField();
        ip = new javax.swing.JTextField();
        JLabel nameLabel = new JLabel();
        JLabel ipLabel = new JLabel();
        JButton sendButton = new JButton();
        JLabel bg = new JLabel(scaledIcon);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1077, 767));

        name.setFont(
                new java.awt.Font("Tw Cen MT Condensed", Font.BOLD | Font.ITALIC, 18)); // NOI18N
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        nameLabel.setFont(new java.awt.Font("Gabriola", Font.BOLD, 18)); // NOI18N
        nameLabel.setText("Name");

        ipLabel.setFont(new java.awt.Font("Gabriola", Font.BOLD, 18)); // NOI18N
        ipLabel.setText("IP Address ");

        sendButton.setText("SUBMIT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1077, Short.MAX_VALUE)
                        .addGroup(
                                layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(
                                                layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addGroup(
                                                                layout.createParallelGroup(
                                                                                javax.swing
                                                                                        .GroupLayout
                                                                                        .Alignment
                                                                                        .LEADING)
                                                                        .addGroup(
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(
                                                                                                nameLabel,
                                                                                                javax
                                                                                                        .swing
                                                                                                        .GroupLayout
                                                                                                        .PREFERRED_SIZE,
                                                                                                90,
                                                                                                javax
                                                                                                        .swing
                                                                                                        .GroupLayout
                                                                                                        .PREFERRED_SIZE)
                                                                                        .addGap(
                                                                                                80,
                                                                                                80,
                                                                                                80)
                                                                                        .addComponent(
                                                                                                name,
                                                                                                javax
                                                                                                        .swing
                                                                                                        .GroupLayout
                                                                                                        .PREFERRED_SIZE,
                                                                                                90,
                                                                                                javax
                                                                                                        .swing
                                                                                                        .GroupLayout
                                                                                                        .PREFERRED_SIZE))
                                                                        .addGroup(
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(
                                                                                                ipLabel,
                                                                                                javax
                                                                                                        .swing
                                                                                                        .GroupLayout
                                                                                                        .PREFERRED_SIZE,
                                                                                                90,
                                                                                                javax
                                                                                                        .swing
                                                                                                        .GroupLayout
                                                                                                        .PREFERRED_SIZE)
                                                                                        .addGap(
                                                                                                80,
                                                                                                80,
                                                                                                80)
                                                                                        .addComponent(
                                                                                                ip,
                                                                                                javax
                                                                                                        .swing
                                                                                                        .GroupLayout
                                                                                                        .PREFERRED_SIZE,
                                                                                                90,
                                                                                                javax
                                                                                                        .swing
                                                                                                        .GroupLayout
                                                                                                        .PREFERRED_SIZE))
                                                                        .addGroup(
                                                                                layout.createSequentialGroup()
                                                                                        .addGap(
                                                                                                70,
                                                                                                70,
                                                                                                70)
                                                                                        .addComponent(
                                                                                                sendButton,
                                                                                                javax
                                                                                                        .swing
                                                                                                        .GroupLayout
                                                                                                        .PREFERRED_SIZE,
                                                                                                130,
                                                                                                javax
                                                                                                        .swing
                                                                                                        .GroupLayout
                                                                                                        .PREFERRED_SIZE)))
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(
                                                bg,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addContainerGap(
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(
                                                bg,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 767, Short.MAX_VALUE)
                        .addGroup(
                                layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(
                                                layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addGroup(
                                                                layout.createParallelGroup(
                                                                                javax.swing
                                                                                        .GroupLayout
                                                                                        .Alignment
                                                                                        .LEADING)
                                                                        .addComponent(
                                                                                nameLabel,
                                                                                javax.swing
                                                                                        .GroupLayout
                                                                                        .PREFERRED_SIZE,
                                                                                30,
                                                                                javax.swing
                                                                                        .GroupLayout
                                                                                        .PREFERRED_SIZE)
                                                                        .addComponent(
                                                                                name,
                                                                                javax.swing
                                                                                        .GroupLayout
                                                                                        .PREFERRED_SIZE,
                                                                                30,
                                                                                javax.swing
                                                                                        .GroupLayout
                                                                                        .PREFERRED_SIZE))
                                                        .addGap(10, 10, 10)
                                                        .addGroup(
                                                                layout.createParallelGroup(
                                                                                javax.swing
                                                                                        .GroupLayout
                                                                                        .Alignment
                                                                                        .LEADING)
                                                                        .addComponent(
                                                                                ipLabel,
                                                                                javax.swing
                                                                                        .GroupLayout
                                                                                        .PREFERRED_SIZE,
                                                                                30,
                                                                                javax.swing
                                                                                        .GroupLayout
                                                                                        .PREFERRED_SIZE)
                                                                        .addComponent(
                                                                                ip,
                                                                                javax.swing
                                                                                        .GroupLayout
                                                                                        .PREFERRED_SIZE,
                                                                                30,
                                                                                javax.swing
                                                                                        .GroupLayout
                                                                                        .PREFERRED_SIZE))
                                                        .addGap(110, 110, 110)
                                                        .addComponent(
                                                                sendButton,
                                                                javax.swing.GroupLayout
                                                                        .PREFERRED_SIZE,
                                                                60,
                                                                javax.swing.GroupLayout
                                                                        .PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(
                                                bg,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addContainerGap()));

        pack();
//        setVisible(true);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        ClientIP(ip.getText());
        ClientName(name.getText());
        System.exit(1);
    }

    // End of variables declaration
}
