package com.github.TeamRocketBalleBalle.Ricktionary.Client;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author tiwar
 */
public class winnerscreen extends javax.swing.JFrame {

    /**
     * Creates new form winnerscreen
     */
    public winnerscreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        ImageIcon icon = new ImageIcon("Client/src/main/resources/tenor.gif");
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(1077, 767, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);

        back = new javax.swing.JLabel("hemlo");
        winnergif = new javax.swing.JLabel();
        back.setIcon(scaledIcon);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1077, 767));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(395, 395, 395)
                                        .addComponent(
                                                winnergif,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                301,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                // .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 1080,
                // javax.swing.GroupLayout.PREFERRED_SIZE)
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(773, 773, 773)
                                        .addComponent(
                                                winnergif,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                154,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                // .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 1010,
                // javax.swing.GroupLayout.PREFERRED_SIZE)
                );
        Rectangle rect = new Rectangle(1077, 767);
        back.setBounds(rect);
        add(back);
        pack();
    } // </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException
                | InstantiationException
                | IllegalAccessException
                | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(winnerscreen.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new winnerscreen().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel back;
    private javax.swing.JLabel winnergif;
    // End of variables declaration
}
