@startuml
actor Client as Client
participant Server as Server
database Room as Room
Client ->Server : Connect
Server -> Client : Connection Accepted; connect to this room
Client -> Room : Client connects to the room

Room -> Client : Load this Hash image
Room -> AllClients : Starts Game
@enduml
